### ISSUE TITLE
使用了之后Chrome不能上网

### ISSUE THREAD

**Issue by QunjunLIANG** [qin-ziqi/SetupVPN#1]
按照README的方法成功安装了 SetupVPN，并且可以科学上网。

但是在一个月之后，发现Chrome不能上网，SetupVPN也无法连接到服务器，不过win10自带的Edge还可以。

查看了很多网上资料，更改internet选项无效，清空DNS缓存无效，重装Chrome也无效。

请问有什么建议吗？

**Comment by qin-ziqi** [comment]
有可能是版本过期了吧，已更新到3.8.8版本。你可以把之前的插件删掉，重新装一下新版本试试
